apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: engine-worker-8573
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/engine-worker-8573
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
